package com.LibraryManagementSystem.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "books") // Ensure table name is lowercase unless specified otherwise
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "book_id", insertable = false, updatable = false)
    private Integer bookId;

    private String bookName;
    private String author;

    @ManyToOne // Many books can be borrowed by many members
    @JoinColumn(name = "book_id") // Join with the book_id column
    private Member member; // Should be Member type, not Book

    @OneToMany(mappedBy = "book", cascade = CascadeType.ALL)
    private List<Loan> loans = new ArrayList<>();

    // Getters and setters are generated by Lombok @Data
}
