package com.LibraryManagementSystem.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Entity
@Table(name = "loans") // Ensure table name is lowercase unless specified otherwise
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Loan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private LocalDate loanDate;
    private LocalDate returnDate;

    @ManyToOne // Many loans can belong to one book
    @JoinColumn(name = "book_id") // Join with the book_id column
    private Book book;

    @ManyToOne // Many loans can be made by one member
    @JoinColumn(name = "member_id") // Join with the member_id column
    private Member member;

    // Getters and setters are generated by Lombok @Data
}
